// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj40zZTR3iqH2OvEngEQL0gwjIPQbWgvw',
    appId: '1:950383661231:web:de580393e1294bed3c845a',
    messagingSenderId: '950383661231',
    projectId: 'fir-flutter-codelab-166f1',
    authDomain: 'fir-flutter-codelab-166f1.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-166f1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9KGk3ARNgLOzbL2hgcmFfGfJ5y9OqRQc',
    appId: '1:950383661231:android:9b833363903ca9b83c845a',
    messagingSenderId: '950383661231',
    projectId: 'fir-flutter-codelab-166f1',
    storageBucket: 'fir-flutter-codelab-166f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9XMmLEynpKcKhBi2AeAc-Zp-YVny4FM0',
    appId: '1:950383661231:ios:0bdac809f5804a263c845a',
    messagingSenderId: '950383661231',
    projectId: 'fir-flutter-codelab-166f1',
    storageBucket: 'fir-flutter-codelab-166f1.appspot.com',
    iosClientId: '950383661231-a0tjblahl1pgumisdovbujob2ngjeosf.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9XMmLEynpKcKhBi2AeAc-Zp-YVny4FM0',
    appId: '1:950383661231:ios:0bdac809f5804a263c845a',
    messagingSenderId: '950383661231',
    projectId: 'fir-flutter-codelab-166f1',
    storageBucket: 'fir-flutter-codelab-166f1.appspot.com',
    iosClientId: '950383661231-a0tjblahl1pgumisdovbujob2ngjeosf.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
